import catalogue from '@/data/advancements.json';
import type { RawAdvancementsFile } from '@/lib/serverData';
import type { Advancement, AdvancementProgress, PlayerAdvancement } from '@/lib/types';

/**
 * Measures a player's advancement file against the vanilla catalogue.
 *
 * The server only writes the advancements a player has touched, so their file
 * says what has been earned but not what is left. `src/data/advancements.json`
 * — generated by `scripts/build-advancements.mjs` — is the full list, and this
 * module joins the two into "26 of 126, and here is which".
 *
 * Recipe unlocks are counted but never listed: the server grants them
 * automatically, there are ~1550 of them, and the catalogue leaves them out.
 */

/** Advancements under this prefix are recipe unlocks, granted automatically rather than earned. */
const RECIPE_PREFIX = 'minecraft:recipes/';

const data = catalogue as {
    version: string;
    categories: { key: string; title: string }[];
    advancements: Advancement[];
};

/**
 * The player's entry for an advancement. Ids are namespaced in the save file but
 * not in the catalogue, and `DataVersion` sits alongside them as a bare number.
 */
const entryFor = (file: RawAdvancementsFile, id: string) => {
    const entry = file[`minecraft:${id}`];
    return typeof entry === 'object' && entry !== null ? entry : null;
};

/** The instant the last criterion was met — Minecraft writes `2026-08-22 17:34:48 +0000`. */
const finishedAt = (criteria: Record<string, string>): number | null => {
    const stamps = Object.values(criteria)
        .map((value) => Date.parse(value))
        .filter((value) => !Number.isNaN(value));

    return stamps.length > 0 ? Math.max(...stamps) : null;
};

/**
 * Joins one player's advancement file to the catalogue. A missing file is the
 * same as an empty one: nothing earned, everything still to do.
 */
export const measureAdvancements = (file: RawAdvancementsFile | null): AdvancementProgress => {
    const progress = file ?? {};

    const measured = data.advancements.map((advancement): PlayerAdvancement => {
        const { requirements, steps, ...rest } = advancement;
        const entry = entryFor(progress, advancement.id);
        const criteria = entry?.criteria ?? {};
        const done = entry?.done === true;

        // One group satisfied is one step ticked; a group with alternatives needs
        // only one of them, which is what `some` is doing here.
        const ticked = requirements.map((group) => group.some((name) => name in criteria));

        return {
            ...rest,
            done,
            have: ticked.filter(Boolean).length,
            need: ticked.length,
            completedAt: done ? finishedAt(criteria) : null,
            // Only the checklists get one, and alphabetically: the datapack's own
            // order means nothing to a reader hunting for the biome they're missing.
            checklist: steps
                ? steps.map((name, index) => ({ name, done: ticked[index] })).sort((a, b) => a.name.localeCompare(b.name))
                : [],
        };
    });

    const categories = data.categories.map(({ key, title }) => {
        const entries = measured.filter((advancement) => advancement.category === key);
        return {
            key,
            title,
            done: entries.filter((advancement) => advancement.done).length,
            total: entries.length,
            entries,
        };
    });

    return {
        done: measured.filter((advancement) => advancement.done).length,
        total: measured.length,
        recipes: Object.entries(progress).filter(([id, entry]) => id.startsWith(RECIPE_PREFIX) && typeof entry === 'object' && entry?.done)
            .length,
        categories,
    };
};
