/**
 * Types and helpers for the /recipes recipe book.
 *
 * The dataset is generated by `scripts/build-recipes.mjs` into
 * `public/recipes.json` and fetched as a static asset — see that script for
 * where the upstream data comes from.
 */

const WIKI_BASE = 'https://minecraft.wiki';

export const PAGE_SIZE = 24;

export type Ingredient = string;

interface RecipeBase {
    id: string;
    type: string;
    result: { id: string; count: number };
}

export interface CraftingRecipe extends RecipeBase {
    kind: 'crafting';
    shapeless: boolean;
    grid: Ingredient[];
}

export interface CookingRecipe extends RecipeBase {
    kind: 'cooking';
    input: Ingredient;
    station: string;
    experience: number;
    cookingTime: number;
}

export interface StonecuttingRecipe extends RecipeBase {
    kind: 'stonecutting';
    input: Ingredient;
    station: string;
}

export interface SmithingRecipe extends RecipeBase {
    kind: 'smithing';
    template: Ingredient;
    base: Ingredient;
    addition: Ingredient;
}

export type Recipe = CraftingRecipe | CookingRecipe | StonecuttingRecipe | SmithingRecipe;

export interface RecipeData {
    version: string;
    generatedAt: string;
    items: Record<string, string>;
    icons: Record<string, string>;
    tags: Record<string, string[]>;
    recipes: Recipe[];
}

export interface RecipeGroup {
    itemId: string;
    name: string;
    recipes: Recipe[];
    searchable: string;
}

export const RECIPE_LABELS: Record<string, string> = {
    crafting_shaped: 'Crafting',
    crafting_shapeless: 'Crafting (shapeless)',
    crafting_transmute: 'Crafting (dyeing)',
    smelting: 'Smelting',
    blasting: 'Blasting',
    smoking: 'Smoking',
    campfire_cooking: 'Campfire',
    stonecutting: 'Stonecutting',
    smithing_transform: 'Smithing',
};

export const itemName = (data: RecipeData, id: string): string => data.items[id] ?? id;

/**
 * Inventory sprite hosted by minecraft.wiki. Most follow directly from the
 * display name; the generator records the ones that don't.
 */
export const iconUrl = (data: RecipeData, id: string): string => {
    const file = data.icons[id] ?? `Invicon_${itemName(data, id).replaceAll(' ', '_')}.png`;
    return `${WIKI_BASE}/images/${encodeURI(file)}`;
};

export const wikiUrl = (data: RecipeData, id: string): string =>
    `${WIKI_BASE}/w/${encodeURIComponent(itemName(data, id).replaceAll(' ', '_'))}`;

const GRID_SLOTS = 9;

/** Restores the full 3x3 grid; the generator omits trailing empty slots to keep the file small. */
export const craftingGrid = (recipe: CraftingRecipe): Ingredient[] =>
    recipe.grid.length === GRID_SLOTS ? recipe.grid : [...recipe.grid, ...Array<Ingredient>(GRID_SLOTS - recipe.grid.length).fill('')];

/** Expands an ingredient slot to the concrete items that satisfy it. */
export const resolveIngredient = (data: RecipeData, ingredient: Ingredient): string[] => {
    if (!ingredient) return [];
    return ingredient.split('|').flatMap((entry) => (entry.startsWith('#') ? (data.tags[entry.slice(1)] ?? []) : [entry]));
};

/** Ticks are Minecraft's 20-per-second time unit. */
export const formatTicks = (ticks: number): string => `${(ticks / 20).toFixed(ticks % 20 === 0 ? 0 : 1)}s`;

/** Crafting is what people look for first, so lead with it and keep the rest in a stable order. */
const KIND_ORDER: Recipe['kind'][] = ['crafting', 'smithing', 'cooking', 'stonecutting'];

const ingredientsOf = (recipe: Recipe): Ingredient[] => {
    if (recipe.kind === 'crafting') return recipe.grid;
    if (recipe.kind === 'smithing') return [recipe.template, recipe.base, recipe.addition];
    return [recipe.input];
};

/**
 * Collapses the flat recipe list into one entry per resulting item, so that
 * e.g. Iron Ingot shows its crafting, smelting and blasting recipes together.
 */
export const groupRecipes = (data: RecipeData): RecipeGroup[] => {
    const groups = new Map<string, RecipeGroup>();

    for (const recipe of data.recipes) {
        const itemId = recipe.result.id;
        let group = groups.get(itemId);
        if (!group) {
            group = { itemId, name: itemName(data, itemId), recipes: [], searchable: '' };
            groups.set(itemId, group);
        }
        group.recipes.push(recipe);

        const names = ingredientsOf(recipe)
            .flatMap((ingredient) => resolveIngredient(data, ingredient))
            .map((id) => itemName(data, id));
        group.searchable += `${names.join(' ')} `;
    }

    for (const group of groups.values()) {
        group.searchable = [...new Set(group.searchable.toLowerCase().split(' '))].join(' ');
        group.recipes.sort((a, b) => KIND_ORDER.indexOf(a.kind) - KIND_ORDER.indexOf(b.kind) || a.id.localeCompare(b.id));
    }
    return [...groups.values()].sort((a, b) => a.name.localeCompare(b.name));
};

/**
 * Ranks a group against the query: an exact name match beats a prefix match,
 * which beats a word-start match, which beats a substring. Ingredient matches
 * rank last so searching "redstone" lists redstone items before the many
 * things merely built from it. Returns null when nothing matches.
 */
const score = (group: RecipeGroup, query: string): number | null => {
    const name = group.name.toLowerCase();
    if (name === query) return 0;
    if (name.startsWith(query)) return 1;
    if (name.includes(` ${query}`)) return 2;
    if (name.includes(query)) return 3;
    if (group.searchable.includes(query)) return 4;
    return null;
};

export const searchGroups = (groups: RecipeGroup[], query: string): RecipeGroup[] => {
    const trimmed = query.trim().toLowerCase();
    if (!trimmed) return groups;

    return groups
        .flatMap((group) => {
            const rank = score(group, trimmed);
            return rank === null ? [] : [{ group, rank }];
        })
        .sort((a, b) => a.rank - b.rank || a.group.name.localeCompare(b.group.name))
        .map(({ group }) => group);
};
